config/routes.rb
Rails.application.routes.draw do

  

  namespace :admin do
    root 'application#index'

    get 'users/:user_id/products/user_products', to: 'products#user_products', as: :products_of_user
    
    
    patch 'shops/:id/approve', to: 'shops#approve', as: :approve_shop
    patch 'shops/:id/disapprove', to: 'shops#disapprove', as: :disapprove_shop

    patch 'shops/:shop_id/products/:id/approve', to: 'products#approve', as: :approve_product
    patch 'shops/:shop_id/products/:id/disapprove', to: 'products#disapprove', as: :disapprove_product

    patch 'users/:user_id/shopless_products/:id/approve', to: 'shopless_products#approve', as: :approve_shopless_product
    patch 'users/:user_id/shopless_products/:id/disapprove', to: 'shopless_products#disapprove', as: :disapprove_shopless_product

     get 'users/:user_id/shops/user_shops', to: 'shops#user_shops', as: :seller_shops

    resources :users do 
      member do
        patch :switch_to_buyer
        patch :switch_to_seller
        patch :suspend_user_account
        patch :reverse_user_suspension
        patch :switch #switch admin user
        patch :revoke #revoke admin rights
      end

      collection do 
        get :suspended_accounts
        get :table_of_admins
      end
    end
    
    resources :users, only: [] do 
      resources :products, except: [:index]
    end
    
    resources :users, only: [] do 
      resources :shops, except: [:index]
    end

    resources :shops, only: [] do 
      resources :products
    end
    
    resources :users do 
      resources :shopless_products
    end

    resources :products, only: [:index, :show]
    resources :shops, only: [:index, :show, :edit, :update, :destroy]
    resources :shopless_products, except: [:index, :new, :create] do
      member do
        get :add
      end
    end
    resources :orders, only: [:index, :show]
    resources :searches, only: [:show, :new, :create]

    get 'buyers', to: 'users#buyers'
    get 'sellers', to: 'users#sellers'
    delete 'products', to: 'products#remove', as: :remove_product_tag
    delete 'shopless_products', to: 'shopless_products#remove', as: :remove_shopless_product_tag
  end

  get 'my_shops', to: 'shops#my_shops', as: :my_shops
  get 'my_products', to: 'products#my_products', as: :my_products
  get 'categorization', to: "products#categorization"

  delete 'shopless_products', to: 'shopless_products#remove', as: :remove_shopless_product_tag
  delete 'products', to: 'products#remove', as: :remove_product_tag

  devise_for :users, controllers: { registrations: "registrations", omniauth_callbacks: "omniauth_callbacks" }
  as :user do  
    patch 'users/:id/switch_to_buyer', to: 'users#switch_to_buyer', as: :switch_to_buyer 
    patch 'users/:id/switch_to_seller', to: 'users#switch_to_seller', as: :switch_to_seller
    get 'users/:id', to: 'users#show', as: :user_profile   
  end

  root 'products#index'

  resources :shopless_products do 
    member do 
      get :add
    end

    collection do 
      get :add_all
    end
  end

  resources :products do 
  end
   
  resources :searches, only: [:show, :new, :create]
  
  resources :shops do 
    resources :products
  end

  resources :orders do
    collection do 
      get :prospective_orders, as: :prospective
    end

    member do 
      patch :serve_order, as: :serve
    end
  end

  
  get '/auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  match "/404", :to => "errors#not_found", :via => :all
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  mount_uploader :image, ShopImageUploader
  belongs_to :user
  has_many :products, dependent: :destroy

  validates :name, :description, :location, :opening, :closing, :user_id, presence: true
  

  # for seo-friendly urls
  def to_param
    "#{self.id}-#{self.name.parameterize}"
  end

  def approve
  	self.update(approved: true)
  	save
  end

  def disapprove
  	self.update(approved: false)
  	save
  end

  def self.search(search)
    if search
      where(["lower(name || ' ' || location) LIKE ?", "%#{search.downcase}%"]) 
    else
      all
    end 
  end
end

app/controllers/admin/shops_controller.rb
class Admin::ShopsController < Admin::ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy, :approve, :disapprove]
  before_action :set_user, except: [:index, :show, :approve, :disapprove]

  def index
  	@shops = Shop.all.search(params[:search]).uniq
  end

  def show
  	@shop_products = @shop.products.all.order(price: :asc)
  end

  def new
  	@shop = Shop.new
  end

  def create
  	@shop = @user.shops.new(shop_params)

  	if @shop.save
  	  flash[:notice] = "Your shop was created successfully!"
  	  redirect_to [:admin, @user, @shop]
  	else
  	  flash.now[:alert] = "Failed to create shop"
  	  render "new"
  	end
  end

  def edit
  end

  def update
  	if @shop.update(shop_params)
  	  flash[:notice] = "Your shop was successfully updated!"
  	  redirect_to [:admin, @user, @shop]
  	else
  	  flash.now[:alert] = "Your failed to update your shop"
  	  render "edit"
  	end
  end

  def destroy
  	@shop.destroy
  	flash[:notice] = "shop record destroyed successfully!"
  	redirect_to admin_shops_path
  end

  def approve
    if @shop.user.suspended?
      flash[:alert] = "Sorry, you can't approve a shop of a suspended user"
      redirect_to :back  
    else
      @shop.approve
      ShopApprovalJob.set(wait: 5.seconds).perform_later(@shop.user, @shop)
      redirect_to :back
    end
  end

  def disapprove
    @shop.disapprove
    ShopDisapprovalJob.set(wait: 5.seconds).perform_later(@shop.user, @shop)
    redirect_to :back
  end

  def user_shops
    @shops = @user.shops.all.order(created_at: :asc)  
  end

  
  private

  def shop_params
  	params.require(:shop).permit(:name, :description, :location, :opening, :closing, :image, :approved, :user_id)
  end

  def set_shop
  	@shop = Shop.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "sorry, could not find the shop record you are looking for.."
    redirect_to admin_root_path
  end

  def set_user
    @user = User.find(params[:user_id])
rescue ActiveRecord::RecordNotFound
	flash[:alert] = " sorry, could not find the user record you are looking for"
	redirect_to admin_root_path
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @shops = Shop.all.where(approved: true).order(created_at: :asc)
  end
  
  def show
    if current_user
  	  @shop_products = @shop.products.all.order(price: :asc)
    else
      @shop_products = @shop.products.all.where(approved: true).order(price: :asc)
    end
  end

  def new
  	@shop = Shop.new
  end

  def create
  	current_user.update(seller: true) if !current_user.seller?

  	@shop = current_user.shops.new(shop_params)

  	if @shop.save
  	  flash[:notice] = "Your shop was created successfully! Verification and approval of shop will 
      occur within 24-48 hours."

      # notify admins of shop created
      User.all.where(admin: true).each do |admin|
        AdminNotifierForShopCreationJob.set(wait: 5.seconds).perform_later(admin, @shop)
      end

      # notify user of shop created
      ShopCreatedJob.set(wait: 5.seconds).perform_later(current_user, @shop)
  	  redirect_to @shop
  	else
  	  flash.now[:alert] = "Failed to create shop because you submitted an incomplete form.
      Please fill part of the form highlighted in red in order to proceed."
  	  render "new"
  	end
  end

  def edit
  end

  def update
  	if @shop.update(shop_params)
  	  flash[:notice] = "Your shop was successfully updated!"
  	  redirect_to @shop
  	else
  	  flash.now[:alert] = "Failed to update shop because you submitted an incomplete form.
      Please fill part of the form highlighted in red in order to proceed."
  	  render "edit"
  	end
  end

  def destroy
  	@shop.destroy
  	flash[:alert] = "do you want to remove this shop? Removing this shop will delete all associated products!"
  	redirect_to new_shop_path
  end

  def my_shops
  	@shops = current_user.shops.all.order(created_at: :asc) if current_user 
  end


  private

  def shop_params
  	params.require(:shop).permit(:name, :description, :location, :opening, :closing, :image, :approved, :user_id)
  end

  def set_shop
  	@shop = Shop.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "sorry, could not find the record you are looking for."
    redirect_to root_path
  end
end

app/helpers/admin/shops_helper.rb
module Admin::ShopsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.erb
<%= simple_form_for shop do |f| %>
  
  <%= f.input :name %>
  <%= f.input :description, maxlength: 800 %>
  <%= f.input :location %>
  <label><strong>Opening Time</strong></label>
  <%= f.time_select :opening, prompt: {hour: 'Choose hour', minute: 'Choose minute', second: 'Choose seconds'}, label: "Time", :minute_step => 30, :ampm => true, :item_wrapper_class => "inline" %>
  <br><br>
  <label><strong>Closing Time</strong></label>
  <%= f.time_select :closing, prompt: {hour: 'Choose hour', minute: 'Choose minute', second: 'Choose seconds'}, label: "Time", :minute_step => 30, :ampm => true, :item_wrapper_class => "inline" %>
  <%= f.input :image %>
  <%= f.input :image_cache, as: :hidden %>
  <br>

  <div class="text-center" style="padding-top:5%;">
    <%= f.button :submit, class: "buy_now" %>
  </div>
<% end %>

app/views/shops/edit.html.erb
<div class="form_container">
	<div class="row">
		<div class="col-lg-10 col-lg-offset-2 col-sm-12 col-xs-12" style="background-color:#000000;">
			<section class="panel">
				<header class="panel-heading">
					<h2 class="panel-title text-center">Edit Your Shop Here!</h2> 
				</header>
				<div class="panel-body">
					<%= render "form", shop: @shop %>
				</div>
			</section>
		</div>
	</div>
</div>

app/views/shops/index.html.erb
<% if @shops.any? %>
<h1>Welcome! Here are our available shops you can explore</h1>
<% else %>
<h1>No shops to explore currently.</h1>
<% end %>  
<div class="list-of-shops">
  <% @shops.each do |shop| %>
  <%= link_to shop do %>
  <div class="shop">
    <div class="row">
      <div class="col-md-6">

        <%= image_tag shop.image_url(:thumb), size: "160x120" %>
      </div>

      <div class="col-md-6">
        <div>
          <h1 class="shop-name"><%= shop.name %></h1>
          <p>Shop Owner: 
            <% if !(shop.user.first_name && shop.user.last_name) %>
            <%= shop.user.fullname %></p>
            <% else %>
            <%= shop.user.first_name %>, <%= shop.user.last_name.first %></p>
            <% end %>
            <% if shop.approved? %>
            <span class="label label-success"><i class="fa fa-check-circle" aria-hidden="true">Verified</i></span></h1>
            <% else %>
            <span class="label label-warning"><i class="fa fa-question-circle" aria-hidden="true">Not Verified</i></span></h1> 
            <% end %>
            <br>
            <p class="created-at"> In a operation since <%= shop.created_at.strftime("%B %d, %Y") %></p>
            <p class="location"><%= shop.location %></p>
            <% if current_user && shop.user == current_user %>
            <p><%= pluralize(shop.products.count, "product") %></p>
            <% elsif !current_user || current_user != shop.user %>
            <p><%= pluralize(shop.products.where(approved: true).count, "product") %></p>
            <% end %> 
          </div>

        </div>
      </div>
    </div>
    <% end %>
    <% end %>
  </div>

app/views/shops/my_shops.html.erb
<div class="container-of-shops">

<% if @shops.empty? %>
  <h1>You Currently Have No Shops. Click <%= link_to "Here", new_shop_path %> to create a shop.</h1>
<% else %>
  <h1>Welcome! Here are your available shops you can explore <%= link_to fa_icon("plus", class: "pull-right") + "add another shop ", new_shop_path, class: "buy_now" %></h1>
<% end %>
<div class="list-of-shops">
<% @shops.each do |shop| %>
<%= link_to shop do %>
<div class="shop">

  <%= image_tag shop.image_url(:thumb), size: "160x120" %>
<div class="shop-details">
    <h1 class="shop-name"><%= shop.name %></h1>
    <p>Shop Owner: <%= shop.user.last_name %>, <%= shop.user.first_name.first %></p>
    <% if shop.approved? %>
        <span class="label label-success"><i class="fa fa-check-circle" aria-hidden="true">Verified</i></span></h1>
    <% else %>
        <span class="label label-warning"><i class="fa fa-question-circle" aria-hidden="true">Not Verified</i></span></h1> 
    <% end %>
    <br>
    <p class="created-at"> In a operation since <%= shop.created_at.strftime("%B %d, %Y") %></p>
    <p class="location"><%= shop.location %></p>
    <p><%= pluralize(shop.products.count, "product") %></p>
</div>
</div>
<% end %>
<% end %>
</div>
</div>

app/views/shops/new.html.erb
<div class="form_container">
	<div class="row">
		<div class="col-lg-10 col-lg-offset-2 col-sm-12 col-xs-12" style="background-color:#000000;">
			<section class="panel">
				<header class="panel-heading">
					<h2 class="panel-title text-center">Welcome! Create a Shop Here!</h2> 
					<h4 class="text-center">Or proceed to <%= link_to fa_icon("arrow-circle-right", class: "pull-right") + " Upload Your Cake", new_shopless_product_path, class: "buy_now" %></h4>
				</header>
				<div class="panel-body">
					<%= render "form", shop: @shop %>
				</div>
			</section>
		</div>
	</div>
</div>

app/views/shops/show.html.erb
<div class="shop-banner-image" %>
		<%= image_tag @shop.image_url(:shop_banner), size: "984x362" %>
	</div>
	<br>
	<div class="row">
		<div class="shop-description-mini col-md-6">
			<h1 class="shop-title"><%= @shop.name %> 
			<% if @shop.approved? %>
			  <span class="label label-success"><i class="fa fa-check-circle" aria-hidden="true">Verified</i></span></h1>
			<% else %>
			  <span class="label label-warning"><i class="fa fa-question-circle" aria-hidden="true">Not Verified</i></span></h1> 
			<% end %>
			<br>
			<p class="shop-description-heading">Description</p>
			<div class="shop-description">
				<p><%= truncate(@shop.description, :length => 100) %>
				<% if @shop.description.length > 100 %>
				<!-- Button trigger modal -->
				<button type="button" class="buy_now" data-toggle="modal" data-target="#shopDescription">
					Read More..
				</button>
				<% end %>
				</p>
			</div>	
			<br>
			<% if current_user && (@shop.user == current_user) %>
			<p><%= link_to fa_icon("pencil") + " Edit Shop Details", [:edit, @shop], class: "buy_now" %>   <%= link_to fa_icon("arrow-circle-right") + " Upload Your Products", new_shop_product_path(@shop), class: "buy_now" if @shop.approved? %>
			<% end %>		
			</p>
		</div>
		<div class="other-shop-details col-md-6">
			<div class="shop-info">
				<div class="shop-hours">
					<p>Opening Hours: <span class="buy_now"><%= @shop.opening.strftime("%l %M %p") %> - <%= @shop.closing.strftime("%l %M %p") %></span></p>
				</div>
				<div class="shop-address">
					<h4>location: <span class="buy_now"><%= @shop.location %></span></h4>
				</div>

				<div class="shop-owner-details">
					<p>Owner: <span class="buy_now"><%= @shop.user.first_name %>, <%= @shop.user.last_name %></span></p>
					<p>Phone number: <button type="button" class="buy_now" data-toggle="modal" data-target="#phoneNumber">
					<i class="fa fa-eye" aria-hidden="true"></i> phonenumber
				</button></p>
					<p>Email: <button type="button" class="buy_now" data-toggle="modal" data-target="#email">
					<i class="fa fa-eye" aria-hidden="true"></i> email
				</button></p>
				</div>
			</div>
		</div>
	</div>
	<br>
	<br>

	<h1>
		
		  <% if current_user && current_user.products.where(shop_id: nil).any? && @shop.user == current_user && @shop.approved? %>
		  <span class="buy_now" style="font-size:14px;"">NOTE: you have <%= pluralize(current_user.products.where(shop_id: nil).count, "product") %> that do not belong to any shop? Click <%= link_to "Here", shopless_products_path(shop_id: @shop.id) %> to view the products and add them to this shop!</span>
		  <% elsif current_user && (current_user.products.where(shop_id: nil).any? || current_user.products.empty?) && @shop.user == current_user && !@shop.approved? %>
		  <span class="buy_now" style="font-size:14px;"">NOTE: Your shop has been created and is pending approval. This means you can't add any product to this shop in the meantime until it has been approved.</span>
		  <% elsif current_user && current_user.products.any? %>
		    All Products by <%= @shop.name %>	
		  <% elsif (!current_user || @shop.user != current_user) &&  @shop.products.empty? %>
		  	All Products by <%= @shop.name %>
		    <p>No products currently listed.</p>
		  <% elsif !current_user && @shop.products.empty? %>
		    <p>No products available</p>
		  <% elsif !current_user && @shop.products.any? %>
		    All Products by <%= @shop.name %>
		  <% end %>
	</h1>

	<div class="shop-products">
		<% @shop_products.in_groups_of(3, false).each do |group| %>
		<div class="product-row">
			<% group.each do |product| %>

			<div class="col_1_of_3 span_1_of_3">
				<div class="view view-fifth">
					<div class="top_box">
						<h3 class="text-center"><%= product.name %></h3>
						<%= link_to shop_product_path(product.shop, product) do %>
						<div class="grid_img">
							<div class="css3"><%= (image_tag (product.imageone_url(:large) || "noimage.jpg"), size: "200x200") %></div>
							<% end %>
							<div class="mask">
								<!--  <div class="info">Quick View</div> -->
							</div>
						</div>
						<div class="price">GHS <%= product.price %></div>
						<p>Cake Maker: 
							<% if product.user %>
							<span class="buy_now"><%= product.user.first_name %>, <%= product.user.last_name %></span>
							<% else %>  
							<span class="buy_now"><%= product.shop.user.first_name %>, <%= product.shop.user.last_name %></span>
							<% end %>  
						</p>
						<% if product.approved? %>
						<span class="label-success"><i class="fa fa-check-circle" aria-hidden="true">Verified</i></span></h1>
						<% else %>
						<span class="label-warning"><i class="fa fa-question-circle" aria-hidden="true">Not Verified</i></span>
						<% end %>
					</div>
				</div>
				<!-- <span class="rating">
					<input type="radio" class="rating-input" id="rating-input-1-5" name="rating-input-1">
					<label for="rating-input-1-5" class="rating-star1"></label>
					<input type="radio" class="rating-input" id="rating-input-1-4" name="rating-input-1">
					<label for="rating-input-1-4" class="rating-star1"></label>
					<input type="radio" class="rating-input" id="rating-input-1-3" name="rating-input-1">
					<label for="rating-input-1-3" class="rating-star1"></label>
					<input type="radio" class="rating-input" id="rating-input-1-2" name="rating-input-1">
					<label for="rating-input-1-2" class="rating-star"></label>
					<input type="radio" class="rating-input" id="rating-input-1-1" name="rating-input-1">
					<label for="rating-input-1-1" class="rating-star"></label>&nbsp;
				</span>
				<ul class="list">
					<li>
						<%#= image_tag "plus.png", alt: "" %>
						<ul class="icon1 sub-icon1 profile_img">
							<li><a class="active-icon c1" href="#">Add To Bag </a>
								<ul class="sub-icon1 list">
									<li><h3>add to cart</h3><a href=""></a></li>
									<li><p>or add to wishlist<a href="">?</a></p></li>
								</ul>
							</li>
						</ul>
					</li>
				</ul> -->
				<div class="clear"></div>
			</a>
		</div>
		<% end %>
	</div>
	<% end %>

	
</div>
</div>

<!-- Modal -->
<div class="modal fade" id="shopDescription" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Shop Description</h4>
      </div>
      <div class="modal-body">
        <%= @shop.description %>
      </div>
      <div class="modal-footer">
        <button type="button" class="buy_now" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="phoneNumber" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Phone Number</h4>
      </div>
      <div class="modal-body">
        <%= @shop.user.phonenumber %>
      </div>
      <div class="modal-footer">
        <button type="button" class="buy_now" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>


<!-- Modal -->
<div class="modal fade" id="email" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Email</h4>
      </div>
      <div class="modal-body">
        <%= @shop.user.email %>
      </div>
      <div class="modal-footer">
        <button type="button" class="buy_now" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>