config/routes.rb
Rails.application.routes.draw do

  

  namespace :admin do
    root 'application#index'

    get 'users/:user_id/products/user_products', to: 'products#user_products', as: :products_of_user
    
    
    patch 'shops/:id/approve', to: 'shops#approve', as: :approve_shop
    patch 'shops/:id/disapprove', to: 'shops#disapprove', as: :disapprove_shop

    patch 'shops/:shop_id/products/:id/approve', to: 'products#approve', as: :approve_product
    patch 'shops/:shop_id/products/:id/disapprove', to: 'products#disapprove', as: :disapprove_product

    patch 'users/:user_id/shopless_products/:id/approve', to: 'shopless_products#approve', as: :approve_shopless_product
    patch 'users/:user_id/shopless_products/:id/disapprove', to: 'shopless_products#disapprove', as: :disapprove_shopless_product

     get 'users/:user_id/shops/user_shops', to: 'shops#user_shops', as: :seller_shops

    resources :users do 
      member do
        patch :switch_to_buyer
        patch :switch_to_seller
        patch :suspend_user_account
        patch :reverse_user_suspension
        patch :switch #switch admin user
        patch :revoke #revoke admin rights
      end

      collection do 
        get :suspended_accounts
        get :table_of_admins
      end
    end
    
    resources :users, only: [] do 
      resources :products, except: [:index]
    end
    
    resources :users, only: [] do 
      resources :shops, except: [:index]
    end

    resources :shops, only: [] do 
      resources :products
    end
    
    resources :users do 
      resources :shopless_products
    end

    resources :products, only: [:index, :show]
    resources :shops, only: [:index, :show, :edit, :update, :destroy]
    resources :shopless_products, except: [:index, :new, :create] do
      member do
        get :add
      end
    end
    resources :orders, only: [:index, :show]
    resources :searches, only: [:show, :new, :create]

    get 'buyers', to: 'users#buyers'
    get 'sellers', to: 'users#sellers'
    delete 'products', to: 'products#remove', as: :remove_product_tag
    delete 'shopless_products', to: 'shopless_products#remove', as: :remove_shopless_product_tag
  end

  get 'my_shops', to: 'shops#my_shops', as: :my_shops
  get 'my_products', to: 'products#my_products', as: :my_products
  get 'categorization', to: "products#categorization"

  delete 'shopless_products', to: 'shopless_products#remove', as: :remove_shopless_product_tag
  delete 'products', to: 'products#remove', as: :remove_product_tag

  devise_for :users, controllers: { registrations: "registrations", omniauth_callbacks: "omniauth_callbacks" }
  as :user do  
    patch 'users/:id/switch_to_buyer', to: 'users#switch_to_buyer', as: :switch_to_buyer 
    patch 'users/:id/switch_to_seller', to: 'users#switch_to_seller', as: :switch_to_seller
    get 'users/:id', to: 'users#show', as: :user_profile   
  end

  root 'products#index'

  resources :shopless_products do 
    member do 
      get :add
    end

    collection do 
      get :add_all
    end
  end

  resources :products do 
  end
   
  resources :searches, only: [:show, :new, :create]
  
  resources :shops do 
    resources :products
  end

  resources :orders do
    collection do 
      get :prospective_orders, as: :prospective
    end

    member do 
      patch :serve_order, as: :serve
    end
  end

  
  get '/auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  match "/404", :to => "errors#not_found", :via => :all
end

app/views/welcome_user/welcome_email.html.erb
<h1>Dear <%= @user.first_name %>,</h1>
<p>Welcome to MakeAndBake. This is a platform where you can 
<% if @user.seller? %> 
upload your products for users to purchase. You can go ahead and create a shop where you can upload cakes associated to your cake shop. No worry if you don't have a shop, you can go ahead and upload your cakes. However, note that creating a cake shop, as well as uploading a cake or related products will have to be approved by us before the public can view. Approval of both shops and products occur within 24 hours.
Thank you
</p>
<% else %>
find all sorts of inspirations when purchasing a cake for that event. There are some many categories of cakes to choose making this platform so rich in variety that you can find any cake for any event guranteed. All cake shops and cake products have been thoroughly verified and thus be assured of quality service on this platform.
Thank you.</p>
<% end %>
Click <%= link_to "here", new_shop_url %> to create your cake shop
Click <%= link_to "here", new_product_url %> to go straight to uploading your cake shops

app/views/welcome_user/welcome_email.text.erb
Dear <%= @user.first_name %>, 
Welcome to MakeAndBake.