config/routes.rb
Rails.application.routes.draw do

  

  namespace :admin do
    root 'application#index'

    get 'users/:user_id/products/user_products', to: 'products#user_products', as: :products_of_user
    
    
    patch 'shops/:id/approve', to: 'shops#approve', as: :approve_shop
    patch 'shops/:id/disapprove', to: 'shops#disapprove', as: :disapprove_shop

    patch 'shops/:shop_id/products/:id/approve', to: 'products#approve', as: :approve_product
    patch 'shops/:shop_id/products/:id/disapprove', to: 'products#disapprove', as: :disapprove_product

    patch 'users/:user_id/shopless_products/:id/approve', to: 'shopless_products#approve', as: :approve_shopless_product
    patch 'users/:user_id/shopless_products/:id/disapprove', to: 'shopless_products#disapprove', as: :disapprove_shopless_product

     get 'users/:user_id/shops/user_shops', to: 'shops#user_shops', as: :seller_shops

    resources :users do 
      member do
        patch :switch_to_buyer
        patch :switch_to_seller
        patch :suspend_user_account
        patch :reverse_user_suspension
        patch :switch #switch admin user
        patch :revoke #revoke admin rights
      end

      collection do 
        get :suspended_accounts
        get :table_of_admins
      end
    end
    
    resources :users, only: [] do 
      resources :products, except: [:index]
    end
    
    resources :users, only: [] do 
      resources :shops, except: [:index]
    end

    resources :shops, only: [] do 
      resources :products
    end
    
    resources :users do 
      resources :shopless_products
    end

    resources :products, only: [:index, :show]
    resources :shops, only: [:index, :show, :edit, :update, :destroy]
    resources :shopless_products, except: [:index, :new, :create] do
      member do
        get :add
      end
    end
    resources :orders, only: [:index, :show]
    resources :searches, only: [:show, :new, :create]

    get 'buyers', to: 'users#buyers'
    get 'sellers', to: 'users#sellers'
    delete 'products', to: 'products#remove', as: :remove_product_tag
    delete 'shopless_products', to: 'shopless_products#remove', as: :remove_shopless_product_tag
  end

  get 'my_shops', to: 'shops#my_shops', as: :my_shops
  get 'my_products', to: 'products#my_products', as: :my_products
  get 'categorization', to: "products#categorization"

  delete 'shopless_products', to: 'shopless_products#remove', as: :remove_shopless_product_tag
  delete 'products', to: 'products#remove', as: :remove_product_tag

  devise_for :users, controllers: { registrations: "registrations", omniauth_callbacks: "omniauth_callbacks" }
  as :user do  
    patch 'users/:id/switch_to_buyer', to: 'users#switch_to_buyer', as: :switch_to_buyer 
    patch 'users/:id/switch_to_seller', to: 'users#switch_to_seller', as: :switch_to_seller
    get 'users/:id', to: 'users#show', as: :user_profile   
  end

  root 'products#index'

  resources :shopless_products do 
    member do 
      get :add
    end

    collection do 
      get :add_all
    end
  end

  resources :products do 
  end
   
  resources :searches, only: [:show, :new, :create]
  
  resources :shops do 
    resources :products
  end

  resources :orders do
    collection do 
      get :prospective_orders, as: :prospective
    end

    member do 
      patch :serve_order, as: :serve
    end
  end

  
  get '/auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  match "/404", :to => "errors#not_found", :via => :all
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  before_action :authorize_admin!
  

  layout "admin"

  def index
    @users = User.all.where(admin: false)
    @buyers = User.all.where(admin: false, seller: false)
    @sellers = User.all.where(admin: false, seller: true)
    @products = Product.all
    @approved_products = Product.where(approved: true)
    @unapproved_products = Product.where(approved: false)
    @orders = Order.all
    @shops = Shop.all
    @shop_owners = User.all.where(admin: false, seller: true).includes(:shops)
    @shopless_owners = User.all.where(admin: false).includes(:shops).where(shops: {user_id: nil})
  end

  private

  def authorize_admin!
  	authenticate_user!

  	unless current_user.admin?
  	  flash[:alert] = "Unauthorized action!! You must be admin to proceed."	
  	  redirect_to root_path	
  	end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username, :fullname, :phonenumber, :gender, :age, :image, :twitter_image, :address,
    	:seller])
    
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :username, :fullname, :phonenumber, :gender, :age, :image, :twitter_image, :address,
    	:seller])
  end

  def after_sign_in_path_for(resource)
    if current_user.admin?
      admin_root_path
    elsif current_user.seller?
      my_shops_path
    elsif !current_user.seller?
      root_path
    end
  end
end

app/helpers/admin/application_helper.rb
module Admin::ApplicationHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/application/index.html.erb
<div class="row">
				<div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
				 <%= link_to admin_users_path do %> 
					<div class="info-box blue-bg">
						<i class="fa fa-users"></i>
						<div class="count"><%= @users.count %></div>
						<div class="title">All Users</div>						
					</div><!--/.info-box-->			
					<% end %>
				</div><!--/.col-->
				
				<div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
				<%= link_to admin_buyers_path do %>
					<div class="info-box yellow-bg">
						<i class="fa fa-user"></i>
						<div class="count"><%= @buyers.count %></div>
						<div class="title">All Buyers</div>						
					</div><!--/.info-box-->			
				<% end %>
				</div><!--/.col-->	
				
				<div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
				<%= link_to admin_sellers_path do %>
					<div class="info-box green-bg">
						<i class="fa fa-user"></i>
						<div class="count"><%= @sellers.count %></div>
						<div class="title">All Sellers</div>						
					</div><!--/.info-box-->			
				<% end %>
				</div><!--/.col-->

				<div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
				<%= link_to admin_products_path do %>
					<div class="info-box brown-bg">
						<i class="fa fa-shopping-cart"></i>
						<div class="count"><%= @products.count %></div>
						<div class="title">All Products</div>						
					</div><!--/.info-box-->			
				<% end %>
				</div><!--/.col-->	

				<div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
				<%= link_to admin_orders_path do %>
					<div class="info-box dark-bg">
						<i class="fa fa-book"></i>
						<div class="count"><%= @orders.count %></div>
						<div class="title">All Orders</div>						
					</div><!--/.info-box-->
				<% end %>			
				</div><!--/.col-->
				
				<div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
				<%= link_to admin_shops_path do %>
					<div class="info-box green-bg">
						<i class="fa fa-home"></i>
						<div class="count"><%= @shops.count %></div>
						<div class="title">All Shops</div>						
					</div><!--/.info-box-->		
				<% end %>	
				</div><!--/.col-->

				<div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
				<%= link_to "#", data: {confirm: "functionality not available yet"} do %>
					<div class="info-box red-bg">
						<i class="fa fa-users"></i>
						<div class="count"><%= @shop_owners.count %></div>
						<div class="title">Shop Owners</div>						
					</div><!--/.info-box-->	
				<% end %>		
				</div><!--/.col-->

				<div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
				<%= link_to "#", data: {confirm: "functionality not available yet"} do %>
					<div class="info-box blue-bg">
						<i class="fa fa-users"></i>
						<div class="count"><%= @shopless_owners.count %></div>
						<div class="title">Shopless Owners</div>						
					</div><!--/.info-box-->	
				<% end %>		
				</div><!--/.col-->
				
			</div><!--/.row-->
		