config/routes.rb
Rails.application.routes.draw do

  

  namespace :admin do
    root 'application#index'

    get 'users/:user_id/products/user_products', to: 'products#user_products', as: :products_of_user
    
    
    patch 'shops/:id/approve', to: 'shops#approve', as: :approve_shop
    patch 'shops/:id/disapprove', to: 'shops#disapprove', as: :disapprove_shop

    patch 'shops/:shop_id/products/:id/approve', to: 'products#approve', as: :approve_product
    patch 'shops/:shop_id/products/:id/disapprove', to: 'products#disapprove', as: :disapprove_product

    patch 'users/:user_id/shopless_products/:id/approve', to: 'shopless_products#approve', as: :approve_shopless_product
    patch 'users/:user_id/shopless_products/:id/disapprove', to: 'shopless_products#disapprove', as: :disapprove_shopless_product

     get 'users/:user_id/shops/user_shops', to: 'shops#user_shops', as: :seller_shops

    resources :users do 
      member do
        patch :switch_to_buyer
        patch :switch_to_seller
        patch :suspend_user_account
        patch :reverse_user_suspension
        patch :switch #switch admin user
        patch :revoke #revoke admin rights
      end

      collection do 
        get :suspended_accounts
        get :table_of_admins
      end
    end
    
    resources :users, only: [] do 
      resources :products, except: [:index]
    end
    
    resources :users, only: [] do 
      resources :shops, except: [:index]
    end

    resources :shops, only: [] do 
      resources :products
    end
    
    resources :users do 
      resources :shopless_products
    end

    resources :products, only: [:index, :show]
    resources :shops, only: [:index, :show, :edit, :update, :destroy]
    resources :shopless_products, except: [:index, :new, :create] do
      member do
        get :add
      end
    end
    resources :orders, only: [:index, :show]
    resources :searches, only: [:show, :new, :create]

    get 'buyers', to: 'users#buyers'
    get 'sellers', to: 'users#sellers'
    delete 'products', to: 'products#remove', as: :remove_product_tag
    delete 'shopless_products', to: 'shopless_products#remove', as: :remove_shopless_product_tag
  end

  get 'my_shops', to: 'shops#my_shops', as: :my_shops
  get 'my_products', to: 'products#my_products', as: :my_products
  get 'categorization', to: "products#categorization"

  delete 'shopless_products', to: 'shopless_products#remove', as: :remove_shopless_product_tag
  delete 'products', to: 'products#remove', as: :remove_product_tag

  devise_for :users, controllers: { registrations: "registrations", omniauth_callbacks: "omniauth_callbacks" }
  as :user do  
    patch 'users/:id/switch_to_buyer', to: 'users#switch_to_buyer', as: :switch_to_buyer 
    patch 'users/:id/switch_to_seller', to: 'users#switch_to_seller', as: :switch_to_seller
    get 'users/:id', to: 'users#show', as: :user_profile   
  end

  root 'products#index'

  resources :shopless_products do 
    member do 
      get :add
    end

    collection do 
      get :add_all
    end
  end

  resources :products do 
  end
   
  resources :searches, only: [:show, :new, :create]
  
  resources :shops do 
    resources :products
  end

  resources :orders do
    collection do 
      get :prospective_orders, as: :prospective
    end

    member do 
      patch :serve_order, as: :serve
    end
  end

  
  get '/auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  match "/404", :to => "errors#not_found", :via => :all
end

app/models/search.rb
class Search < ActiveRecord::Base
    
  
  def search_products
    
    products = Product.where(approved: true).order(price: :asc).all

    products = products.where(["lower(name) LIKE ?", "%#{keywords.downcase}%"]) if keywords.present?
    # products = Product.where(["name LIKE ?", name]) if name.present?
    products = products.where(["price >= ?", min_price]) if min_price.present?
    products = products.where(["price <= ?", max_price]) if max_price.present?
    products = products.where(["lower(size) LIKE ?", "%#{size.downcase}%"]) if size.present?
    # products_by_tags = Product.joins(:tags).where(tags: { name: name })
    products = products.joins(:tags).where(tags: { name: "#{category.downcase}" }) if category.present?


    products
  end

   def admin_search_products
    
    products = Product.order(price: :asc).all

    products = products.where(["lower(name) LIKE ?", "%#{keywords.downcase}%"]) if keywords.present?
    products = products.where(["price >= ?", min_price]) if min_price.present?
    products = products.where(["price <= ?", max_price]) if max_price.present?
    products = products.where(["lower(size) LIKE ?", "%#{size.downcase}%"]) if size.present?
    # products_by_tags = Product.joins(:tags).where(tags: { name: name })
    products = products.joins(:tags).where(tags: { name: "#{category.downcase}" }) if category.present?


    products
  end
end

app/controllers/admin/searches_controller.rb
class Admin::SearchesController < Admin::ApplicationController
  
  def show
  	@search = Search.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "Oops! search result failed for some reason"
    render "new"
  end

  def new
  	@search = Search.new
  	# @product_categories = Tag.uniq.pluck(:name)
  end

  def create
  	@search = Search.create(search_params)
  	redirect_to [:admin, @search]
  end

  

  private

  def search_params
  	params.require(:search).permit(:keywords, :name, :max_price, :min_price, :size, :category)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def show
  	@search = Search.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "Oops! search result failed for some reason"
    render "new"
  end

  def new
  	@search = Search.new
  	# @product_categories = Tag.uniq.pluck(:name)
  end

  def create
  	@search = Search.create(search_params)
  	redirect_to @search 
  end

  

  private

  def search_params
  	params.require(:search).permit(:keywords, :name, :max_price, :min_price, :size, :category)
  end
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/new.html.erb
<br>
<div class="login-title">
<h4 class="title">Advanced Search By:</h4>

<%= form_for @search, html: { class: "pure-form" } do |f| %>
<div class="row">
  <div class="col-md-2 col-lg-4 col-sm-2 col-xs-2">
  <div class="fields">
    <%= f.label :keywords, "name of cake" %>
    <%= f.text_field :keywords, class: "form-control" %>  	
  </div>

  <div class="fields">
    <%= f.label :min_price, "min price of cake"%> <%=  f.text_field :min_price, size: 10, class: "form-control" %>	
  </div>

  <div class="fields">
    <%= f.label :max_price, "max price"%> <%=  f.text_field :max_price, size: 10, class: "form-control" %>
  </div>

  <div class="fields">
    <%= f.label :size, "size of cake(small, medium, or large)" %>
    <%= f.text_field :size, class: "form-control" %>
  </div>

  <div class="fields">
    <%= f.label :category, "category(e.g by events, type of cake, etc)" %>
    <%= f.text_field :category, class: "form-control" %>
  </div>

   <div class="fields">
    <%#= f.label :name, "Categories" %>
    <%#= f.select :name, options_for_select(@product_categories), :include_blank => true %> 
  </div>
  </div>
  </div>
  </div>
  <br>

  <div class="actions">
    <%= f.submit "Search", class: "search_button" %>	
  </div>
<% end %>
<br>

<%= link_to fa_icon("arrow-left") + " Back", :back, class: "back_button" %>

app/views/searches/show.html.erb
<h2>Search Result(s)</h2>
<br>
<%= link_to fa_icon("arrow-left") + " Back", :back, class: "back_button" %>
<br>

<% if @search.search_products.empty? %>
  <p>No Records Found</p>
<% else %>
  <% @search.search_products.in_groups_of(3, false).each do |group| %>
<div class="row">
<% group.each do |product| %>

<div class="col_1_of_3 span_1_of_3">
 <div class="view view-fifth">
  <div class="top_box">
    <h3 class="text-center"><%= product.name %></h3>
    <div class="grid_img">
     <div class="css3">
     <% if product.shop %>
     <%= link_to (image_tag product.imageone_url(:large), size: "250x200"), admin_shop_product_path(product.shop, product) %>
     <% else %>
     <%= link_to (image_tag product.imageone_url(:large), size: "250x200"), admin_user_shopless_product_path(product.user, product) %>
     <% end %>  
     </div>
     <div class="mask">
      <!-- <div class="info">Quick View</div> -->
    </div>
  </div>
  <div class="price">GHS <%= product.price %></div>
  <p>Cake Maker: 
  <% if product.user %>
      <% if !(product.user.first_name && product.user.last_name) %>
          <span class="buy_now"><%= product.user.fullname %></span>
        <% else %>
        <span class="buy_now"><%= product.user.first_name %>, <%= product.user.last_name %></span></h4>
      <% end %>
    <% elsif product.shop %>
      <% if !(product.shop.user.first_name && product.shop.user.last_name) %>
        <span class="buy_now"><%= product.shop.user.fullname %></span>
      <% else %>
      <span class="buy_now"><%= product.shop.user.first_name %>, <%= product.shop.user.last_name %></span>  
      <% end %>
    <% end %>
</div>
</div>
<!-- <span class="rating">
  <input type="radio" class="rating-input" id="rating-input-1-5" name="rating-input-1">
  <label for="rating-input-1-5" class="rating-star1"></label>
  <input type="radio" class="rating-input" id="rating-input-1-4" name="rating-input-1">
  <label for="rating-input-1-4" class="rating-star1"></label>
  <input type="radio" class="rating-input" id="rating-input-1-3" name="rating-input-1">
  <label for="rating-input-1-3" class="rating-star1"></label>
  <input type="radio" class="rating-input" id="rating-input-1-2" name="rating-input-1">
  <label for="rating-input-1-2" class="rating-star"></label>
  <input type="radio" class="rating-input" id="rating-input-1-1" name="rating-input-1">
  <label for="rating-input-1-1" class="rating-star"></label>&nbsp;
</span>
<ul class="list">
  <li>
    <%#= image_tag "plus.png", alt: "" %>
    <ul class="icon1 sub-icon1 profile_img">
      <li><a class="active-icon c1" href="#">Add To Bag </a>
        <ul class="sub-icon1 list">
          <li><h3>add to cart</h3><a href=""></a></li>
          <li><p>or add to wishlist<a href="">?</a></p></li>
        </ul>
      </li>
    </ul>
  </li>
</ul> -->
<div class="clear"></div>
</a></div>
<% end %>
</div>
<% end %>

<% end %>